plugins {
    id 'com.android.library'
    id 'maven-publish'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.vifarmer.ads.lib'
    compileSdk 35

    defaultConfig {
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"

        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
            withJavadocJar()
        }
    }

    buildFeatures {
        buildConfig = true
        viewBinding = true
    }

    buildTypes {
        release {
            buildConfigField "String", "apiKey", "\"Bearer mpBYiG4WNndUpojp7pez\""
            buildConfigField "String", "baseUrl", "\"https://api.adjust.com/device_service/api/v1/\""
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            buildConfigField "String", "apiKey", "\"Bearer mpBYiG4WNndUpojp7pez\""
            buildConfigField "String", "baseUrl", "\"https://api.adjust.com/device_service/api/v1/\""
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    lint {
        checkReleaseBuilds false
        abortOnError false
    }
}

tasks.withType(GenerateModuleMetadata).configureEach {
    enabled = false
}

tasks.whenTaskAdded { task ->
    if (task.name.contains("bundleReleaseLocalLintAar")) {
        task.enabled = false
    }
}

//publishing {
//    publications {
//        release(MavenPublication) {
//            groupId = 'com.github.DuongNT3012'
//            artifactId = 'com.vifarmer.ads.lib'
//            version = '1.0.0'
//
//            afterEvaluate {
//                from components.release
//            }
//        }
//    }
//}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.lifecycle:lifecycle-process:2.9.1'
    implementation 'androidx.core:core-ktx:1.16.0'
    implementation 'com.google.android.play:review:2.0.2'
    implementation 'com.google.android.play:app-update:2.1.0'
    implementation 'androidx.activity:activity:1.10.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
    //image to text
    implementation 'com.google.android.gms:play-services-vision:20.1.3'
    //sdk fb
    implementation 'com.facebook.android:facebook-android-sdk:18.2.3'
    // Retrofit
    implementation 'com.squareup.retrofit2:retrofit:3.0.0'
    implementation 'com.squareup.retrofit2:converter-gson:3.0.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:5.3.2'
    //ads
    implementation 'com.google.android.gms:play-services-ads:25.2.0'
    implementation 'com.google.android.gms:play-services-ads-identifier:18.3.0'
    implementation 'com.google.android.gms:play-services-appset:16.1.0'
    //implementation 'com.google.android.gms:play-services-basement:18.7.0'
    implementation 'com.android.installreferrer:installreferrer:2.2'
    //adjust
    implementation 'com.adjust.sdk:adjust-android:5.7.0'
    //firebase
    implementation platform('com.google.firebase:firebase-bom:34.13.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-config'
    //shimmer fb
    implementation 'com.facebook.shimmer:shimmer:0.5.0'
    //
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.10.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.10.0'
    implementation 'com.airbnb.android:lottie:6.7.1'
    //billing
    implementation "com.android.billingclient:billing:9.0.0"
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                // components.release chứa toàn bộ file .aar và dependencies của module này
                from components.release

                // GroupId: Thường là com.github.User
                groupId = 'com.github.DuongNT3012'
                // ArtifactId: Phải là AmazicLibrary để gọi được implementation ngắn gọn
                artifactId = 'AmazicLibrary'
                // Version: Lấy theo Git Tag, ở đây set cứng để Gradle đồng bộ local
                version = '2.4.0'

                // Fix lỗi "Missing required attribute: dependency groupId"
//                pom.withXml {
//                    def dependenciesNode = asNode().getAt('dependencies')[0]
//                    if (dependenciesNode != null) {
//                        // Lặp qua tất cả các dependency trong file POM được sinh ra
//                        def dependencies = dependenciesNode.getAt('dependency')
//                        dependencies.each { dep ->
//                            def groupId = dep.getAt('groupId').text()
//                            // Nếu groupId bị thiếu hoặc là 'unspecified' (do file AAR cục bộ)
//                            if (groupId == null || groupId == "" || groupId == "unspecified") {
//                                // XÓA NÓ ĐI khỏi file POM
//                                dependenciesNode.remove(dep)
//                            }
//                        }
//                    }
//                }
            }
        }
    }
}
