apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

android {
    compileSdk rootProject.ext.compileSdkVersion
    namespace "com.google.ads.mediation.sample.customevent"

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0.0.0"
        buildConfigField("String", "ADAPTER_VERSION", "\"${versionName}\"")
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
            withJavadocJar()
        }
    }
    buildFeatures {
        buildConfig = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

publishing {
    publications {
        release(MavenPublication) {
            groupId = 'com.github.DuongNT3012'
            artifactId = 'com.google.ads.mediation.sample.customevent'
            version = '1.0.0'

            afterEvaluate {
                from components.release
            }
        }
    }
}

dependencies {
    implementation project(':sdk')
    implementation rootProject.ext.playServicesAds
    implementation rootProject.ext.appcompat
    implementation platform('com.google.firebase:firebase-bom:33.12.0')
    implementation 'com.google.firebase:firebase-analytics'
}
